Repository monsieurbiz/SyliusRichEditorPlugin, pull requests merged in 2020-11, with the labels that each got.

#69 Manage collection type with images
  assets/js/app.js
  src/Controller/FormController.php
  src/Form/Constraints/RichEditorConstraints.php
  src/Form/Type/UiElement/DoubleImageType.php
  src/Form/Type/UiElement/ImageCollectionType.php
  src/Form/Type/UiElement/ImageType.php
  src/Form/Type/UiElement/VideoType.php
  src/Resources/config/config.yaml
  src/Resources/public/js/rich-editor-js.js
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/app.html.twig
  src/Resources/views/Form/theme.html.twig
  src/Resources/views/Shop/UiElement/image_collection.html.twig
Labels: Status: needs review

#67 Remove product and taxon products elements
  src/Form/Type/UiElement/OldElement/ProductsType.php
  src/Form/Type/UiElement/OldElement/TaxonProductType.php
  src/Repository/ProductRepository.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Shop/UiElement/OldElement/products.html.twig
  src/Resources/views/Shop/UiElement/OldElement/taxon_product.html.twig
  src/UiElement/OldElement/Products.php
  src/UiElement/OldElement/TaxonProduct.php
Labels: Status: needs review

#68 Add Youtube Element
  src/Form/Type/UiElement/YoutubeType.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Shop/UiElement/youtube.html.twig
  src/Twig/RichEditorExtension.php
  src/Validator/Constraints/YoutubeUrl.php
  src/Validator/Constraints/YoutubeUrlValidator.php
Labels: Status: needs review

#70 Deprecate double image type
  src/Form/Type/UiElement/OldElement/DoubleImageType.php
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Shop/UiElement/OldElement/double_image.html.twig
  src/UiElement/OldElement/DoubleImage.php
Labels: Status: needs review

#73 Use translation for confirm delete message
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review, quick win

#74 Make image field in video element non required
  src/Form/Type/UiElement/VideoType.php
Labels: Status: needs review, quick win

#72 Add default HTML element
  assets/js/app.js
  src/Form/Type/UiElement/HtmlType.php
  src/Resources/config/config.yaml
  src/Resources/public/js/rich-editor-js.js
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/UiElement/html.html.twig
  src/Resources/views/Admin/app.html.twig
  src/Resources/views/Shop/UiElement/html.html.twig
Labels: Status: needs review

#76 Remove unused RenderUiElementEvent
  src/Controller/FormController.php
  src/Event/RenderUiElementEvent.php
  src/Twig/RichEditorExtension.php
Labels: Status: needs review, enhancement, quick win

#75 Use Sylius UI events instead of sonata block
  src/EventListener/Admin/AppBlock.php
  src/Resources/config/config.yaml
  src/Resources/config/services.yaml
  src/Resources/config/sylius/ui.yaml
Labels: Status: needs review, enhancement, quick win

#78 Update README and images
  README.md
  screenshots/button.png
  screenshots/button_link.png
  screenshots/carousel.png
  screenshots/demo.gif
  screenshots/double_image.png
  screenshots/form_field.png
  screenshots/full_back.png
  screenshots/full_front.png
  screenshots/gmap_element.png
  screenshots/gmap_form.png
  screenshots/gmap_render.png
  screenshots/gmap_render_admin.png
  screenshots/html.png
  screenshots/image.png
  screenshots/image_collection.png
  screenshots/products.png
  screenshots/quote.png
  screenshots/separator.png
  screenshots/taxon_product.png
  screenshots/text.png
  screenshots/title.png
  screenshots/video.png
  screenshots/youtube.png
Labels: Status: needs review

#79 Return empty render if UI element does not exists to make JS works
  src/Controller/FormController.php
Labels: Status: needs review, quick win

#80 Remove deprecated or unused code
  src/Form/Type/UiElement/OldElement/DoubleImageType.php
  src/Form/Type/UiElement/OldElement/ProductsType.php
  src/Form/Type/UiElement/OldElement/TaxonProductType.php
  src/Kernel.php
  src/Repository/ProductRepository.php
  src/Resources/config/config.yaml
  src/Resources/config/routing.yaml
  src/Resources/config/routing/partial.yaml
  src/Resources/config/services.yaml
  src/Resources/views/Admin/UiElement/double_image.html.twig
  src/Resources/views/Shop/UiElement/OldElement/double_image.html.twig
  src/Resources/views/Shop/UiElement/OldElement/products.html.twig
  src/Resources/views/Shop/UiElement/OldElement/taxon_product.html.twig
  src/Resources/views/Shop/_carousel.html.twig
  src/Resources/views/Shop/_taxon_button.html.twig
  src/Resources/views/Shop/js.html.twig
  src/UiElement/OldElement/AbstractUiElement.php
  src/UiElement/OldElement/ButtonLink.php
  src/UiElement/OldElement/DoubleImage.php
  src/UiElement/OldElement/Image.php
  src/UiElement/OldElement/Products.php
  src/UiElement/OldElement/Quote.php
  src/UiElement/OldElement/Separator.php
  src/UiElement/OldElement/TaxonProduct.php
  src/UiElement/OldElement/Text.php
  src/UiElement/OldElement/Title.php
  src/UiElement/OldElement/Video.php
  src/UiElement/YoutubeVideoTrait.php
Labels: Status: needs review

#77 Some PHPSpec tests
  phpspec.yml.dist
  src/UiElement/Metadata.php
  tests/spec/UiElement/MetadataSpec.php
  tests/spec/UiElement/UiElementSpec.php
Labels: Status: needs review, documentation, enhancement

#81 Fix build of assets in test Application
  .gitignore
  Makefile
  yarn.lock
Labels: Status: needs review, bug, enhancement, quick win

#82 Allow scrolling in the panels content
  assets/css/app.scss
  assets/js/app.js
  src/Resources/public/css/rich-editor-css.css
  src/Resources/public/js/rich-editor-js.js
  src/Resources/views/Admin/form.html.twig
Labels: Status: needs review, quick win

#84 Prepare 2.0 by merging master
  README.md
  src/Resources/views/Admin/UiElement/button.html.twig
  src/Resources/views/Admin/UiElement/quote.html.twig
  src/Resources/views/Admin/UiElement/separator.html.twig
  src/Resources/views/Admin/UiElement/text.html.twig
  src/Resources/views/Admin/UiElement/title.html.twig
  src/Resources/views/Admin/UiElement/video.html.twig
Labels: Status: needs review, enhancement, quick win

#85 Some improvements before 2.0!
  .github/workflows/recipe.yaml
  .github/workflows/tests.yaml
  Makefile
  TESTING.md
  recipes/2.0-dev/config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml
  src/Controller/FormController.php
  src/Resources/config/config.yaml
  src/Resources/config/richeditor.yaml
  src/Resources/config/routing.yaml
  src/Resources/config/services.yaml
  src/UiElement/Metadata.php
  tests/spec/UiElement/MetadataSpec.php
  tests/spec/UiElement/UiElementSpec.php
Labels: Status: needs review, documentation, enhancement, quick win

#88 Correct README setup with correct file content for routing and config
  README.md
  recipes/2.0-dev/config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml
Labels: Status: needs review, quick win

#89 Use an autowired UiElement
  README.md
  src/Controller/FormController.php
  src/DependencyInjection/UiElementRegistryPass.php
  src/Twig/RichEditorExtension.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementTrait.php
  tests/Application/config/packages/monsieurbiz_sylius_rich_editor_plugin_custom.yaml
  tests/Application/src/Form/Type/UiElement/GoogleMapsType.php
  tests/Application/src/UiElement/GoogleMapsUiElement.php
  tests/Application/templates/Admin/UiElement/google_maps.html.twig
  tests/Application/templates/Shop/UiElement/google_maps.html.twig
  tests/Application/translations/messages.en.yaml
Labels: Status: needs review, enhancement, quick win

#90 Manage empty value in input when it has no element
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
Labels: Status: needs review, quick win

#91 Reduce cyclomatic complexity
  src/Controller/FormController.php
  src/Twig/RichEditorExtension.php
  src/Validator/Constraints/YoutubeUrlValidator.php
Labels: Status: needs review, enhancement, quick win

#92 Add tags filtering
  README.md
  assets/js/app.js
  src/DependencyInjection/Configuration.php
  src/Form/Type/RichEditorType.php
  src/Resources/public/js/rich-editor-js.js
  src/UiElement/Metadata.php
  src/UiElement/MetadataInterface.php
  src/UiElement/UiElementTrait.php
  tests/spec/UiElement/MetadataSpec.php
Labels: Status: needs review, enhancement

#101 Add a notice about removed Ui Elements into UPGRADE-2.0.md
  UPGRADE-2.0.md
Labels: Status: needs review, quick win

#102 Update README badges
  README.md
Labels: Status: needs review, quick win

#100 Enable overflow scroll on edit dialog
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
Labels: Status: needs review

#112 Only close panels with a CTA
  assets/css/app.scss
  assets/js/app.js
  src/Resources/public/css/rich-editor-css.css
  src/Resources/public/js/rich-editor-js.js
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/app.html.twig
Labels: enhancement

#96 Update v2 upgrade docs
  UPGRADE-2.0.md
Labels: documentation

#114 Remove HTML tags when pasting a content from clipboard into the wysiwyg
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
Labels: Status: needs review, quick win

#117 Use pell inside the Wysiwyg object
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review, bug, quick win

#118 Add h1/h2/h3 elements
  src/Resources/config/richeditor.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/UiElement/h1.html.twig
  src/Resources/views/Admin/UiElement/h2.html.twig
  src/Resources/views/Admin/UiElement/h3.html.twig
  src/Resources/views/Shop/UiElement/h1.html.twig
  src/Resources/views/Shop/UiElement/h2.html.twig
  src/Resources/views/Shop/UiElement/h3.html.twig
Labels: Status: needs review, quick win

#119 Add description in Ui Element cards in Selection panel
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review, enhancement, quick win
