Repository monsieurbiz/SyliusRichEditorPlugin, pull requests merged in 2020-10, with the labels that each got.

#36 Use the RichEditorType in test application
  src/Form/Type/RichEditorType.php
  tests/Application/src/Form/Extension/ProductTypeExtension.php
Labels: Status: needs review, enhancement

#37 Add root .editorconfig
  .editorconfig
Labels: Status: needs review, enhancement, quick win

#38 Allow Github Actions on all PRs
  .github/workflows/tests.yaml
Labels: Status: needs review, quick win

#40 Remove Twig Extension tests before 2.0
  tests/RichEditorServiceProvider.php
  tests/Twig/Extension/RichEditorExtensionTest.php
  tests/Twig/Fixtures/rich_editor_empty_data.legacy.test
  tests/Twig/Fixtures/rich_editor_empty_data.test
  tests/Twig/Fixtures/rich_editor_full_data.legacy.test
  tests/Twig/Fixtures/rich_editor_full_data.test
  tests/Twig/Fixtures/rich_editor_fulltext_data.legacy.test
  tests/Twig/Fixtures/rich_editor_fulltext_data.test
  tests/Twig/Fixtures/rich_editor_noelements_data.legacy.test
  tests/Twig/Fixtures/rich_editor_noelements_data.test
Labels: Status: needs review

#41 New UI Element Management
  src/Application/MonofonyPluginTrait.php
  src/Controller/ModalController.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MonsieurBizSyliusRichEditorExtension.php
  src/DependencyInjection/UiElementRegistryPass.php
  src/Factory/UiElementFactory.php
  src/MonsieurBizSyliusRichEditorPlugin.php
  src/Resources/config/config.yaml
  src/Resources/config/services.yaml
  src/Twig/RichEditorExtension.php
  src/UiElement/AbstractUiElement.php
  src/UiElement/Metadata.php
  src/UiElement/Metadata/Registry.php
  src/UiElement/Metadata/RegistryInterface.php
  src/UiElement/MetadataInterface.php
  src/UiElement/Registry.php
  src/UiElement/RegistryInterface.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review, enhancement

#44 Fix incorrect registry namespace
  src/Resources/config/services.yaml
Labels: Status: needs review, quick win

#45 Use php instead of run to execute tests in Makefile
  Makefile
Labels: Status: needs review, quick win

#43 Twig list UI elements
  README.md
  src/Twig/RichEditorExtension.php
  src/UiElement/Registry.php
  src/UiElement/RegistryInterface.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review

#46 Remove v1 useless features in v2
  src/Controller/ModalController.php
  src/EventListener/Admin/AppBlock.php
  src/Exception/UndefinedUiElementTypeException.php
  src/Factory/UiElementFactory.php
  src/Factory/UiElementFactoryInterface.php
  src/Resources/config/config.yaml
  src/Resources/config/routing.yaml
  src/Resources/config/routing/admin.yaml
  src/Resources/config/routing/partial.yaml
  src/Resources/config/services.yaml
  src/Resources/views/Admin/app.html.twig
  src/Resources/views/UiElement/products.html.twig
  src/Resources/views/UiElement/taxon_product.html.twig
  src/Twig/RichEditorExtension.php
  src/UiElement/OldElement/AbstractUiElement.php
  src/UiElement/OldElement/ButtonLink.php
  src/UiElement/OldElement/DoubleImage.php
  src/UiElement/OldElement/Image.php
  src/UiElement/OldElement/Products.php
  src/UiElement/OldElement/Quote.php
  src/UiElement/OldElement/Separator.php
  src/UiElement/OldElement/TaxonProduct.php
  src/UiElement/OldElement/Text.php
  src/UiElement/OldElement/Title.php
  src/UiElement/OldElement/Video.php
  src/UiElement/UiElementInterface.php
  tests/Application/src/Form/Extension/ProductTypeExtension.php
Labels: Status: needs review

#47 Manage Ui Element form display
  recipes/2.0-dev/config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml
  src/Controller/FormController.php
  src/DependencyInjection/Configuration.php
  src/Form/Type/UiElement/TextType.php
  src/Resources/config/config.yaml
  src/Resources/config/routing.yaml
  src/Resources/config/routing/admin.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/Modal/edit.html.twig
  src/Resources/views/Admin/form.html.twig
Labels: Status: needs review

#48 Prefer dist on composer on github actions
  Makefile
Labels: Status: needs review, quick win

#49 Correct deprecated add-path in Github Actions
  .github/workflows/tests.yaml
Labels: Status: needs review, quick win

#42 Improve UI Elements management in admin
  Makefile
  assets/css/app.scss
  assets/js/app.js
  package.json
  src/Resources/config/services.yaml
  src/Resources/public/css/rich-editor-css.css
  src/Resources/public/js/rich-editor-js.js
  src/Resources/views/Admin/app.html.twig
  src/Twig/RichEditorExtension.php
  tests/Application/config/packages/monsieurbiz_sylius_richeditor_plugin_custom.yaml
  tests/Application/package.json
  yarn.lock
Labels: Status: needs review, enhancement

#51 Translate Ui Element's description and title during json serialize
  src/DependencyInjection/UiElementRegistryPass.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review, quick win

#52 Manage Ui Element submit form
  src/Controller/FormController.php
  src/Exception/UiElementNotFoundException.php
  src/Resources/config/routing/admin.yaml
  src/Resources/views/Admin/form.html.twig
Labels: Status: needs review

#53 Migrate quote Ui Element
  src/Form/Type/UiElement/QuoteType.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
Labels: Status: needs review, quick win

#54 Render elements in front
  src/Exception/UiElementNotFoundException.php
  src/Resources/config/config.yaml
  src/Resources/views/Shop/UiElement/button_link.html.twig
  src/Resources/views/Shop/UiElement/double_image.html.twig
  src/Resources/views/Shop/UiElement/image.html.twig
  src/Resources/views/Shop/UiElement/products.html.twig
  src/Resources/views/Shop/UiElement/quote.html.twig
  src/Resources/views/Shop/UiElement/separator.html.twig
  src/Resources/views/Shop/UiElement/taxon_product.html.twig
  src/Resources/views/Shop/UiElement/text.html.twig
  src/Resources/views/Shop/UiElement/title.html.twig
  src/Resources/views/Shop/UiElement/video.html.twig
  src/Twig/RichEditorExtension.php
  tests/Application/config/packages/monsieurbiz_sylius_richeditor_plugin_custom.yaml
  tests/Application/templates/bundles/SyliusShopBundle/Product/Show/Tabs/Details/_description.html.twig
Labels: Status: needs review, enhancement, quick win

#55 Condition up and down to the element's position
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
Labels: Status: needs review, quick win

#50 Add a new UI Element in a Rich Editor field in admin
  assets/js/app.js
  src/Controller/FormController.php
  src/Resources/config/config.yaml
  src/Resources/public/js/rich-editor-js.js
  src/Resources/views/Admin/app.html.twig
  src/Resources/views/Admin/form.html.twig
Labels: Status: needs review, enhancement

#57 Setup the WYSIWYG
  assets/css/app.scss
  assets/js/app.js
  src/Resources/public/css/rich-editor-css.css
  src/Resources/public/js/rich-editor-js.js
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review

#58 Backward compatibility for 1.x
  UPGRADE-2.0.md
  assets/js/app.js
  src/DependencyInjection/Configuration.php
  src/Resources/config/config.yaml
  src/Resources/public/js/rich-editor-js.js
  src/Twig/RichEditorExtension.php
  src/UiElement/Metadata.php
  src/UiElement/MetadataInterface.php
  src/UiElement/Registry.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review, enhancement

#60 Simplify FQDN in UiElement's class
  src/UiElement/UiElementInterface.php
Labels: Status: needs review, quick win

#61 Update symfony.lock
  symfony.lock
Labels: Status: needs review, quick win

#59 Ignore aliased elements
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
  src/UiElement/Registry.php
  src/UiElement/UiElement.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review, bug, quick win

#63 Manage file upload and migrate Image UiElement
  src/Controller/FormController.php
  src/DependencyInjection/MonsieurBizSyliusRichEditorExtension.php
  src/Form/Constraints/RichEditorConstraints.php
  src/Form/Type/UiElement/DoubleImageType.php
  src/Form/Type/UiElement/ImageType.php
  src/Form/Type/UiElement/VideoType.php
  src/Resources/config/config.yaml
  src/Resources/config/services.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/app.html.twig
  src/Resources/views/Form/theme.html.twig
  src/Service/FileUploader.php
  src/UiElement/UiElementInterface.php
Labels: Status: needs review

#64 Migrate Video Element
  src/Form/Constraints/RichEditorConstraints.php
  src/Form/Type/UiElement/VideoType.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
Labels: Status: needs review

#65 Migrate button element
  src/Form/Type/UiElement/ButtonLinkType.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Shop/UiElement/button.html.twig
  src/UiElement/OldElement/ButtonLink.php
Labels: Status: needs review

#66 Migrate title and separator elements
  src/Form/Type/UiElement/SeparatorType.php
  src/Form/Type/UiElement/TitleType.php
  src/Resources/config/config.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
Labels: Status: needs review
