Repository monsieurbiz/SyliusRichEditorPlugin, pull requests merged in 2021-02, with the labels that each got.

#131 Fields are not always required
  src/DependencyInjection/UiElementRegistryPass.php
  src/Form/Type/UiElement/ButtonLinkType.php
  src/Resources/views/Admin/UiElement/button.html.twig
  symfony.lock
Labels: Status: needs review, enhancement, quick win

#130 Allow null to be passed as content to rendering methods in twig
  src/Twig/RichEditorExtension.php
Labels: Status: needs review, enhancement, quick win

#133 Correct Pell behaviour when removing EOL (stop adding font-size in span)
  assets/css/app.scss
  src/Resources/public/css/rich-editor-css.css
Labels: Status: needs review

#134 Add an action in the WYSIWYG to insert a <hr>
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review, quick win

#135 Add alignement field for some elements
  src/Form/Type/AlignmentType.php
  src/Form/Type/UiElement/ButtonLinkType.php
  src/Form/Type/UiElement/ImageType.php
  src/Form/Type/UiElement/QuoteType.php
  src/Form/Type/UiElement/TextType.php
  src/Form/Type/UiElement/TitleType.php
  src/Form/Type/UiElement/VideoType.php
  src/Form/Type/UiElement/YoutubeType.php
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/Admin/UiElement/button.html.twig
  src/Resources/views/Admin/UiElement/h1.html.twig
  src/Resources/views/Admin/UiElement/h2.html.twig
  src/Resources/views/Admin/UiElement/h3.html.twig
  src/Resources/views/Admin/UiElement/image.html.twig
  src/Resources/views/Admin/UiElement/quote.html.twig
  src/Resources/views/Admin/UiElement/text.html.twig
  src/Resources/views/Admin/UiElement/title.html.twig
  src/Resources/views/Admin/UiElement/video.html.twig
  src/Resources/views/Admin/UiElement/youtube.html.twig
  src/Resources/views/Shop/UiElement/button.html.twig
  src/Resources/views/Shop/UiElement/h1.html.twig
  src/Resources/views/Shop/UiElement/h2.html.twig
  src/Resources/views/Shop/UiElement/h3.html.twig
  src/Resources/views/Shop/UiElement/image.html.twig
  src/Resources/views/Shop/UiElement/quote.html.twig
  src/Resources/views/Shop/UiElement/text.html.twig
  src/Resources/views/Shop/UiElement/title.html.twig
  src/Resources/views/Shop/UiElement/video.html.twig
  src/Resources/views/Shop/UiElement/youtube.html.twig
Labels: Status: needs review

#136 Be able to manage WYSIWYG in collection forms
  src/Resources/views/Admin/app.html.twig
Labels: Status: needs review
