Repository monsieurbiz/SyliusRichEditorPlugin, pull requests merged in 2021-08, with the labels that each got.

#155 Add files in fixture utility system
  README.md
  src/Fixture/FileFixture.php
  src/Resources/config/config.yaml
  src/Resources/config/services.yaml
  src/Uploader/FixtureFileUploaderInterface.php
  src/Uploader/FixtureFixtureFileUploader.php
Labels: enhancement, Status: needs update

#158 Use mixed as type
  src/Controller/FormController.php
Labels: Status: needs review, quick win

#159 Some craaaazy changes :p
  symfony.lock
  tests/Application/.gitignore
Labels: Status: needs review, quick win

#160 Add missing getter in object
  assets/js/app.js
  src/Resources/public/js/rich-editor-js.js
Labels: bug, Status: needs review, quick win
